### Updates an existing patient entity
PUT http://localhost:4000/patients/62cec926-ef63-4461-8cb8-fd298f1a4ca7
Content-Type: application/json

{
  "name" : "gagan",
  "email" : "test@gmail.com",
  "address" : "123 main street",
  "dateOfBirth" : "1995-09-09"
}

###